project_id = "pgguejgjpxjqxntlwdck"

[functions.create-admin]
verify_jwt = false

[functions.analyze-complaint]
verify_jwt = false

[functions.get-admin-insights]
verify_jwt = true

[functions.send-complaint-email]
verify_jwt = false

[functions.send-announcement-email]
verify_jwt = false

[functions.send-sms-notification]
verify_jwt = false

[functions.detect-spam-complaint]
verify_jwt = false